#!/usr/bin/env bash
# Regenerate src/libretro.rs from a vendored libretro.h.
#
# The bindings are committed rather than generated by build.rs on purpose: that
# keeps libclang off the list of things every build machine (Windows/CI included)
# needs. Run this by hand when a core update brings in a newer header.
#
# The allowlists matter. Without them bindgen drags in everything libretro.h
# reaches through <stdint.h>/<limits.h> -- ~520 lines of `_POSIX_RE_DUP_MAX`,
# `PTHREAD_KEYS_MAX`, `INT_FAST16_MIN` and friends, none of which we use.
#
# The enum style is bindgen's default (a `c_uint` type alias plus free integer
# constants) and should stay that way. Frontend-side we receive these values as
# raw u32 out of `*mut c_void` handed to us by core code we don't control;
# materializing an out-of-range value into a real Rust enum would be UB, and the
# constants also let `RETROKMOD_* as u16` masks and `retro_key` map keys stay
# plain integers (see src/emulator.rs and src/retro_emu.rs).

set -euo pipefail

cd "$(dirname "$0")/.."

# Both libretro-uae and vice-libretro vendor the same, newest header we have --
# it is the only one carrying the microphone, device-power and netpacket
# interfaces. Anything else under libretro/ is years older.
HEADER="${1:-libretro/libretro-uae/libretro-common/include/libretro.h}"
OUT="src/libretro.rs"

if [[ ! -f "$HEADER" ]]; then
    echo "no such header: $HEADER" >&2
    exit 1
fi

if ! command -v bindgen >/dev/null; then
    echo "bindgen not found; install with: cargo install bindgen-cli" >&2
    exit 1
fi

echo "generating $OUT from $HEADER"

# No `--raw-line` allow(...) preamble: main.rs already carries `#[allow(warnings)]`
# on `mod libretro`. Layout assertions are left on -- they are the only thing
# checking our struct definitions still match the header ABI.
bindgen "$HEADER" \
    --output "$OUT" \
    --allowlist-type '(retro|RETRO)_.*' \
    --allowlist-function '(retro|RETRO)_.*' \
    --allowlist-var '(retro|RETRO)_.*' \
    --no-prepend-enum-name \
    --with-derive-default

echo "wrote $OUT ($(grep -c '' "$OUT") lines)"
